version: "3.2"

services:
  app:
    environment:
      - DATASOURCE_HOST_PORT=postgres:5432
      - DATASOURCE_DBNAME=crown_court_proceeding
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - REPORT_CRON_REACTIVATED_CASES=0 5 8 * * *
      - REPORT_CRON_DROPPED_PROSECUTION=0 10 8 * * *
      - SENTRY_ENV=development
      - SENTRY_SAMPLE_RATE=0.0
      - LOG_LEVEL=DEBUG
    env_file:
      - app.env
    ports:
      - "8081:8081"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081 -jar app.jar

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crown_court_proceeding