--liquibase formatted sql
--changeset Gangadhar Nitta:11-create-reactivated-prosecution-case-table.sql

CREATE SEQUENCE IF NOT EXISTS crown_court_proceeding.REACTIVATE_CASE INCREMENT BY 1 START WITH 1;

CREATE TABLE IF NOT EXISTS crown_court_proceeding.REACTIVATED_PROSECUTION_CASE
(	 ID INTEGER NOT NULL DEFAULT nextval('crown_court_proceeding.REACTIVATE_CASE') PRIMARY KEY,
     MAAT_ID INTEGER,
     CASE_URN VARCHAR(200),
     HEARING_ID VARCHAR(200),
     PREVIOUS_OUTCOME VARCHAR(200),
     PREVIOUS_OUTCOME_DATE TIMESTAMP (6),
     DATE_OF_STATUS_CHANGE TIMESTAMP (6),
     REPORTING_STATUS VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS REACTIVE_CASE_MAAT_ID_STATUS_IDX ON crown_court_proceeding.REACTIVATED_PROSECUTION_CASE (MAAT_ID, REPORTING_STATUS);



