--liquibase formatted sql
--changeset mtac50:11-create-reactivate-prosecution-case-table.sql
CREATE SEQUENCE IF NOT EXISTS REACTIVATED_PROSECUTION_CASE INCREMENT BY 1 START WITH 1;

CREATE TABLE IF NOT EXISTS crown_court_proceeding.PROSECUTION_CONCLUDED_OUTCOME
(	 "ID" INTEGER NOT NULL DEFAULT nextval('REACTIVATED_PROSECUTION_CASE') PRIMARY KEY,
     "MAAT_ID" INTEGER,
     "CASE_URN" VARCHAR(200),
     "HEARING_ID" VARCHAR(200),
     "PREVIOUS_OUTCOME" VARCHAR(200),
     "PREVIOUS_OUTCOME_DATE" TIMESTAMP (6),
     "DATE_OF_STATUS_CHANGE" TIMESTAMP (6),
     "REPORTING_STATUS" VARCHAR(30),
);